config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :photos
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  get 'welcome/index'
  root 'welcome#index'
  get 'myphotos' => 'photos#myphotos'
  get 'photosof/:user_id' => 'photos#photosof', :as => "photosof"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" style="margin-bottom: 0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Instagrama</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="<%= photos_path%>">Fotos <span class="sr-only">(current)</span></a></li>
        <li><a href="<%= myphotos_path%>"> Mis Fotos <span class="sr-only">(current)</span></a></li>
        
      </ul>
      <form class="navbar-form navbar-left" method="GET">
        <div class="form-group">
          <input name="q"<%= @q %> class="form-control" placeholder="buscador">
        </div>
        <button type="submit" class="btn btn-default">Buscar</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.nil? %>
          <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
          <li><a href="<%= new_user_registration_path %>">Registro</a></li>
          <%else%>
            <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
        <%end%>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>