config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :photos
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }
  get 'welcome/index'
  root 'welcome#index'
  get 'myphotos' => 'photos#myphotos'
  get 'photosof/:user_id' => 'photos#photosof', :as => "photosof"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
	belongs_to :user
	has_many :photo_tags
	has_many :tags, through: :photo_tags

	accepts_nested_attributes_for :tags,
		reject_if: proc { |attributes| attributes['name'].blank? },
		allow_destroy: true

	
	validates :content, presence:true
	

	mount_uploader :image, ImagenUploader

	def to_s
		content
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index, :show]

  def photosof
      @user_id = params[:user_id]
      @user = User.find(@user_id)
      @photos = @user.photos
  end

  def myphotos
    @photos = current_user.photos
  end

  # GET /photos
  # GET /photos.json
  def index
    
    @photos = Photo.all

    
    
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
    @photo.tags.build
  end

  # GET /photos/1/edit
  def edit
    @photo.tags.build
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:content, :image, :remote_image_url, :image_cache, :q, tags_attributes: [ :id, :name, :_destroy])
    end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for photo, html: {multipart: true} do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, "Descripción de la Imágen" %>
    <%= f.text_field :content, :class => 'form-control', :placeholder => "Contenido de la foto" %>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :image, "Imágen" %>
      <%= f.file_field :image %>
      <%= f.text_field :remote_image_url, :class => 'form-control' , :placeholder => " ó inserte URL de la imágen" %>
      <%= f.hidden_field :image_cache %>
      <%= image_tag(photo.image) if photo.image? %>
    </div>
  </div>

<h2>Tags</h2>
<%= f.fields_for :tags do |tag| %>
  <div class="field">
    <%= tag.label :name %><br>
    <%= tag.text_field :name %>
    <%= tag.check_box :_destroy %>
    <%= tag.label :_destroy, 'eliminar' %>
  </div>
<% end %>


  <div class="form-group">
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/photos/edit.html.erb
<div class="container">
	<h1>Editar Fotos</h1>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form', photo: @photo %>
		</div>
		
	</div>

	<%= link_to 'Show', @photo %> |
	<%= link_to 'Back', photos_path %>
	
</div>

app/views/photos/index.html.erb
<div class="container">
  <h1>Fotos</h1>

  <% @photos.each do |photo| %>
    <div class="col-md-3">
      <div class="thumbnail">

        <%= photo.content %>
        <%= image_tag(photo.image, :class => 'img-responsive') %>
        <%= photo.tags.collect(&:name).join(", ")%>
        <div class="buttons", style="margin-top:10px; margin-bottom:10px"></div>
        <%= link_to 'Show', photo, :class => 'btn' %>
        <% if can? :edit, photo %>
          <%= link_to 'Edit', edit_photo_path(photo), :class => 'btn' %>
          <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>

        <% if user_signed_in? %>
          
        <% end %>
      </div>
    </div>
    
  <% end %>
    
  <br>
  <% if user_signed_in? %>
    <%= link_to 'New Photo', new_photo_path %>
  <% end %>

</div>

app/views/photos/myphotos.html.erb
<div class="container">
  <h1>Mis Fotos</h1>

  <% @photos.each do |photo| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= photo.content %>
        <%= image_tag(photo.image, :class => 'img-responsive') %>
        <div class="buttons", style="margin-top:10px; margin-bottom:10px"></div>
        <%= link_to 'Show', photo, :class => 'btn' %>
        <%= link_to 'Edit', edit_photo_path(photo), :class => 'btn' %>
        <% if user_signed_in? %>
          <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>
    </div>
    
  <% end %>
    
  <br>
  <% if user_signed_in? %>
    <%= link_to 'New Photo', new_photo_path %>
  <% end %>

</div>

app/views/photos/new.html.erb
<div class="container">
	<h1>Nueva Foto</h1>
	<div class="row">
		<div class="col-md-6">
		<%= render 'form', photo: @photo %>
		</div>
	</div>
	<p><%= link_to 'Back', photos_path %></p>
	
	
</div>

app/views/photos/photosof.html.erb
<% @user_id %>
<div class="container">
  <h1>Mis Fotos</h1>

  <% @photos.each do |photo| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= photo.content %>
        <%= image_tag(photo.image, :class => 'img-responsive') %>
        <div class="buttons", style="margin-top:10px; margin-bottom:10px"></div>
        <%= link_to 'Show', photo, :class => 'btn' %>
        <%= link_to 'Edit', edit_photo_path(photo), :class => 'btn' %>
        <% if user_signed_in? %>
          <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>
    </div>
    
  <% end %>
    
  <br>
  <% if user_signed_in? %>
    <%= link_to 'New Photo', new_photo_path %>
  <% end %>

</div>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @photo.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@photo.image, :style => 'img-responsive') if @photo.image? %>
</p>
<h2>Tags</h2>
<% if @photo.tags.any? %>
<ul>	
	<% @photo.tags.each do |tag|  %>
	<li><%= link_to tag, tag %> </li>
	<% end %>
</ul>
<% else %>
<p>none available</p>
<% end %>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

<%= link_to "Más fotos del usuario", photosof_path(@photo.user.id) %>
		